### Import Library

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sb
import sklearn 
from sklearn import datasets
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier , plot_tree
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report
from imblearn.over_sampling import SMOTE

### Load Data

In [4]:
data = pd.read_csv("creditcard.csv")

### Info of the Dataset

In [6]:
data.info

<bound method DataFrame.info of             Time         V1         V2        V3        V4        V5  \
0            0.0  -1.359807  -0.072781  2.536347  1.378155 -0.338321
1            0.0   1.191857   0.266151  0.166480  0.448154  0.060018
2            1.0  -1.358354  -1.340163  1.773209  0.379780 -0.503198
3            1.0  -0.966272  -0.185226  1.792993 -0.863291 -0.010309
4            2.0  -1.158233   0.877737  1.548718  0.403034 -0.407193
...          ...        ...        ...       ...       ...       ...
284802  172786.0 -11.881118  10.071785 -9.834783 -2.066656 -5.364473
284803  172787.0  -0.732789  -0.055080  2.035030 -0.738589  0.868229
284804  172788.0   1.919565  -0.301254 -3.249640 -0.557828  2.630515
284805  172788.0  -0.240440   0.530483  0.702510  0.689799 -0.377961
284806  172792.0  -0.533413  -0.189733  0.703337 -0.506271 -0.012546

              V6        V7        V8        V9  ...       V21       V22  \
0       0.462388  0.239599  0.098698  0.363787  ... -0.018307  0.277838
1      -0.082361 -0.078803  0.085102 -0.255425  ... -0.225775 -0.638672
2       1.800499  0.791461  0.247676 -1.514654  ...  0.247998  0.771679
3       1.247203  0.237609  0.377436 -1.387024  ... -0.108300  0.005274
4       0.095921  0.592941 -0.270533  0.817739  ... -0.009431  0.798278
...          ...       ...       ...       ...  ...       ...       ...
284802 -2.606837 -4.918215  7.305334  1.914428  ...  0.213454  0.111864
284803  1.058415  0.024330  0.294869  0.584800  ...  0.214205  0.924384
284804  3.031260 -0.296827  0.708417  0.432454  ...  0.232045  0.578229
284805  0.623708 -0.686180  0.679145  0.392087  ...  0.265245  0.800049
284806 -0.649617  1.577006 -0.414650  0.486180  ...  0.261057  0.643078

             V23       V24       V25       V26       V27       V28  Amount  \
0      -0.110474  0.066928  0.128539 -0.189115  0.133558 -0.021053  149.62
1       0.101288 -0.339846  0.167170  0.125895 -0.008983  0.014724    2.69
2       0.909412 -0.689281 -0.327642 -0.139097 -0.055353 -0.059752  378.66
3      -0.190321 -1.175575  0.647376 -0.221929  0.062723  0.061458  123.50
4      -0.137458  0.141267 -0.206010  0.502292  0.219422  0.215153   69.99
...          ...       ...       ...       ...       ...       ...     ...
284802  1.014480 -0.509348  1.436807  0.250034  0.943651  0.823731    0.77
284803  0.012463 -1.016226 -0.606624 -0.395255  0.068472 -0.053527   24.79
284804 -0.037501  0.640134  0.265745 -0.087371  0.004455 -0.026561   67.88
284805 -0.163298  0.123205 -0.569159  0.546668  0.108821  0.104533   10.00
284806  0.376777  0.008797 -0.473649 -0.818267 -0.002415  0.013649  217.00

        Class
0           0
1           0
2           0
3           0
4           0
...       ...
284802      0
284803      0
284804      0
284805      0
284806      0

[284807 rows x 31 columns]>

### Description of Dataset

In [8]:
data.describe()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
count,284807.000000,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,...,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,284807.000000,284807.000000
mean,94813.859575,1.168375e-15,3.416908e-16,-1.379537e-15,2.074095e-15,9.604066e-16,1.487313e-15,-5.556467e-16,1.213481e-16,-2.406331e-15,...,1.654067e-16,-3.568593e-16,2.578648e-16,4.473266e-15,5.340915e-16,1.683437e-15,-3.660091e-16,-1.227390e-16,88.349619,0.001727
std,47488.145955,1.958696e+00,1.651309e+00,1.516255e+00,1.415869e+00,1.380247e+00,1.332271e+00,1.237094e+00,1.194353e+00,1.098632e+00,...,7.345240e-01,7.257016e-01,6.244603e-01,6.056471e-01,5.212781e-01,4.822270e-01,4.036325e-01,3.300833e-01,250.120109,0.041527
min,0.000000,-5.640751e+01,-7.271573e+01,-4.832559e+01,-5.683171e+00,-1.137433e+02,-2.616051e+01,-4.355724e+01,-7.321672e+01,-1.343407e+01,...,-3.483038e+01,-1.093314e+01,-4.480774e+01,-2.836627e+00,-1.029540e+01,-2.604551e+00,-2.256568e+01,-1.543008e+01,0.000000,0.000000
25%,54201.500000,-9.203734e-01,-5.985499e-01,-8.903648e-01,-8.486401e-01,-6.915971e-01,-7.682956e-01,-5.540759e-01,-2.086297e-01,-6.430976e-01,...,-2.283949e-01,-5.423504e-01,-1.618463e-01,-3.545861e-01,-3.171451e-01,-3.269839e-01,-7.083953e-02,-5.295979e-02,5.600000,0.000000
50%,84692.000000,1.810880e-02,6.548556e-02,1.798463e-01,-1.984653e-02,-5.433583e-02,-2.741871e-01,4.010308e-02,2.235804e-02,-5.142873e-02,...,-2.945017e-02,6.781943e-03,-1.119293e-02,4.097606e-02,1.659350e-02,-5.213911e-02,1.342146e-03,1.124383e-02,22.000000,0.000000
75%,139320.500000,1.315642e+00,8.037239e-01,1.027196e+00,7.433413e-01,6.119264e-01,3.985649e-01,5.704361e-01,3.273459e-01,5.971390e-01,...,1.863772e-01,5.285536e-01,1.476421e-01,4.395266e-01,3.507156e-01,2.409522e-01,9.104512e-02,7.827995e-02,77.165000,0.000000
max,172792.000000,2.454930e+00,2.205773e+01,9.382558e+00,1.687534e+01,3.480167e+01,7.330163e+01,1.205895e+02,2.000721e+01,1.559499e+01,...,2.720284e+01,1.050309e+01,2.252841e+01,4.584549e+00,7.519589e+00,3.517346e+00,3.161220e+01,3.384781e+01,25691.160000,1.000000

### head() will give first 5 rows and columns of the Dataset

In [10]:
data.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

### tail() will give last 5 rows and columns of the dataset

In [12]:
data.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
284802,172786.0,-11.881118,10.071785,-9.834783,-2.066656,-5.364473,-2.606837,-4.918215,7.305334,1.914428,...,0.213454,0.111864,1.014480,-0.509348,1.436807,0.250034,0.943651,0.823731,0.77,0
284803,172787.0,-0.732789,-0.055080,2.035030,-0.738589,0.868229,1.058415,0.024330,0.294869,0.584800,...,0.214205,0.924384,0.012463,-1.016226,-0.606624,-0.395255,0.068472,-0.053527,24.79,0
284804,172788.0,1.919565,-0.301254,-3.249640,-0.557828,2.630515,3.031260,-0.296827,0.708417,0.432454,...,0.232045,0.578229,-0.037501,0.640134,0.265745,-0.087371,0.004455,-0.026561,67.88,0
284805,172788.0,-0.240440,0.530483,0.702510,0.689799,-0.377961,0.623708,-0.686180,0.679145,0.392087,...,0.265245,0.800049,-0.163298,0.123205,-0.569159,0.546668,0.108821,0.104533,10.00,0
284806,172792.0,-0.533413,-0.189733,0.703337,-0.506271,-0.012546,-0.649617,1.577006,-0.414650,0.486180,...,0.261057,0.643078,0.376777,0.008797,-0.473649,-0.818267,-0.002415,0.013649,217.00,0

### Checking the Missing value in the Dataset.

In [14]:
''' Checking the Missing Value of the Dataset '''
data.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

### Droping the unnecessary row of the dataset

In [16]:
data=data.drop("Time",axis=1)

### Firstly, we will drop the targets row from the dataset and so, now x contains only the features of the dataset. y contains the targets rows of the dataset.

In [18]:
x = data.drop("Class", axis=1) #dropped targets from dataset so in x only features are remaining
y = data["Class"] #now y have all targets of dataset

In [19]:
''' Features of the Dataset '''
x

,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,0.090794,...,0.251412,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62
1,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,-0.166974,...,-0.069083,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69
2,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,0.207643,...,0.524980,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66
3,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,-0.054952,...,-0.208038,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50
4,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,0.753074,...,0.408542,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
284802,-11.881118,10.071785,-9.834783,-2.066656,-5.364473,-2.606837,-4.918215,7.305334,1.914428,4.356170,...,1.475829,0.213454,0.111864,1.014480,-0.509348,1.436807,0.250034,0.943651,0.823731,0.77
284803,-0.732789,-0.055080,2.035030,-0.738589,0.868229,1.058415,0.024330,0.294869,0.584800,-0.975926,...,0.059616,0.214205,0.924384,0.012463,-1.016226,-0.606624,-0.395255,0.068472,-0.053527,24.79
284804,1.919565,-0.301254,-3.249640,-0.557828,2.630515,3.031260,-0.296827,0.708417,0.432454,-0.484782,...,0.001396,0.232045,0.578229,-0.037501,0.640134,0.265745,-0.087371,0.004455,-0.026561,67.88
284805,-0.240440,0.530483,0.702510,0.689799,-0.377961,0.623708,-0.686180,0.679145,0.392087,-0.399126,...,0.127434,0.265245,0.800049,-0.163298,0.123205,-0.569159,0.546668,0.108821,0.104533,10.00
284806,-0.533413,-0.189733,0.703337,-0.506271,-0.012546,-0.649617,1.577006,-0.414650,0.486180,-0.915427,...,0.382948,0.261057,0.643078,0.376777,0.008797,-0.473649,-0.818267,-0.002415,0.013649,217.00

In [20]:
''' Targets of the Dataset '''
y

0         0
1         0
2         0
3         0
4         0
         ..
284802    0
284803    0
284804    0
284805    0
284806    0
Name: Class, Length: 284807, dtype: int64

### Spliting the dataset into Train Data & Test Data : test_size = 0.2 means that 80% data will be used for training purpose and remaining 20% data will be used for testing purpose. Here, random_state = 0 will make sure that on every split the data remains same

In [22]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

### Scaling / Standardizing / Normalizating the data

In [24]:
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

### SMOTE (Synthetic Minority Over-sampling Technique) is initialized to handle class imbalance by generating synthetic samples of the minority class.

In [26]:
smote = SMOTE(random_state=42)

### Now, SMOTE is applied to the training data to generate synthetic samples of the minority class. This balances the dataset and helps the model learn patterns from both classes effectively.

In [28]:
x_train_sm, y_train_sm = smote.fit_resample(x_train, y_train)

### Comparing the Results in No. of values in class 0 and 1 Before SMOTE and After SMOTE

In [30]:
print("Before SMOTE:\n", y_train.value_counts())
print("\nAfter SMOTE:\n", y_train_sm.value_counts())

Before SMOTE:
 Class
0    227454
1       391
Name: count, dtype: int64

After SMOTE:
 Class
0    227454
1    227454
Name: count, dtype: int64

### Pipeline of SMOTE for implementation

In [32]:
# Split → Scale → SMOTE → Train → Predict → Evaluate

# Logistic Regression

### Before SMOTE

### Creating the Model and Then, Traning the Model.

In [36]:
model = LogisticRegression()
model.fit(x_train, y_train)

LogisticRegression()

### y_pred contains the value which are predicted by the model after testing it through x_test features.

In [38]:
y_pred = model.predict(x_test)
y_pred

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

### y_test contains the target values which were the part of dataset before splitting

In [40]:
y_test

183484    0
255448    0
244749    0
63919     0
11475     0
         ..
236778    0
127073    0
208502    0
263323    0
246221    0
Name: Class, Length: 56962, dtype: int64

### Accuracy of Logistic regression Before SMOTE

In [42]:
print("Accuracy of Logistic regression Before SMOTE : ",accuracy_score(y_pred, y_test))

Accuracy of Logistic regression Before SMOTE :  0.9991748885221726

### Classification Report of Logistic Regression Before SMOTE

In [44]:
print("Classification Report of Logistic Regression Before SMOTE :\n",classification_report(y_test,y_pred))

Classification Report of Logistic Regression Before SMOTE :
               precision    recall  f1-score   support

           0       1.00      1.00      1.00     56861
           1       0.88      0.62      0.73       101

    accuracy                           1.00     56962
   macro avg       0.94      0.81      0.86     56962
weighted avg       1.00      1.00      1.00     56962

### After SMOTE

### Training the Model Again with SMOTE values of the Dataset

In [47]:
model.fit(x_train_sm, y_train_sm)

LogisticRegression()

### y_pred contains the values which are predicted by the model after training with x_test feature value of the dataset

In [49]:
y_pred_sm = model.predict(x_test)
y_pred_sm

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

### y_test contains the target values which were the part of dataset before splitting

In [51]:
y_test

183484    0
255448    0
244749    0
63919     0
11475     0
         ..
236778    0
127073    0
208502    0
263323    0
246221    0
Name: Class, Length: 56962, dtype: int64

### Accuracy Score of Logestic Regression After SMOTE

In [53]:
print("Accuracy Score of Logestic Regression After SMOTE:",accuracy_score(y_pred_sm, y_test))

Accuracy Score of Logestic Regression After SMOTE: 0.9753168779186124

### Classification Report of Logestic Regression After SMOTE

In [55]:
print("Classification Report of Logestic Regression After SMOTE :\n",classification_report(y_test, y_pred_sm))

Classification Report of Logestic Regression After SMOTE :
               precision    recall  f1-score   support

           0       1.00      0.98      0.99     56861
           1       0.06      0.94      0.12       101

    accuracy                           0.98     56962
   macro avg       0.53      0.96      0.55     56962
weighted avg       1.00      0.98      0.99     56962

### After applying SMOTE, the recall for the fraud class increased significantly, meaning the model was able to detect most fraudulent transactions. However, precision decreased, indicating an increase in false positives. This highlights the trade-off between detecting fraud and minimizing false alarms.

# KNN Classifier

### Before SMOTE

### Creating Model

In [60]:
knn = KNeighborsClassifier(n_neighbors=5)

### Training the Model

In [62]:
knn.fit(x_train, y_train)

KNeighborsClassifier()

### y_pred_knn contains the values which are predicted by model after training and testing it with x_test

In [64]:
y_pred_knn = knn.predict(x_test)
y_pred_knn

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

### y_test contains the target values which were the part of dataset before splitting

In [66]:
y_test

183484    0
255448    0
244749    0
63919     0
11475     0
         ..
236778    0
127073    0
208502    0
263323    0
246221    0
Name: Class, Length: 56962, dtype: int64

### Accuracy of KNN Clasifier before SMOTE

In [68]:
print("Accuracy of KNN Before SMOTE: ",accuracy_score(y_test, y_pred_knn))

Accuracy of KNN Before SMOTE:  0.9995259997893332

### Classification Report of KNN Classifier Before SMOTE

In [70]:
print("Classification_Report of KNN Before SMOTE : \n",classification_report(y_test, y_pred_knn))

Classification_Report of KNN Before SMOTE :
               precision    recall  f1-score   support

           0       1.00      1.00      1.00     56861
           1       0.93      0.79      0.86       101

    accuracy                           1.00     56962
   macro avg       0.96      0.90      0.93     56962
weighted avg       1.00      1.00      1.00     56962

### After SMOTE

### Training the model with SMOTE values of the Dataset

In [73]:
knn.fit(x_train_sm, y_train_sm)

KNeighborsClassifier()

### y_pred_knn_sm contains the values which are predicated after training the model and testing it with x_test

In [75]:
y_pred_knn_sm = knn.predict(x_test)
y_pred_knn_sm

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

### y_test contains the target values which were the part of dataset before splitting

In [77]:
y_test

183484    0
255448    0
244749    0
63919     0
11475     0
         ..
236778    0
127073    0
208502    0
263323    0
246221    0
Name: Class, Length: 56962, dtype: int64

### Accuracy of KNN Classifier after SMOTE

In [79]:
print("Accuracy of KNN after SMOTE : ",accuracy_score(y_test, y_pred_knn_sm))

Accuracy of KNN after SMOTE :  0.9982268881008391

### Classification Report of KNN Classifier after SMOTE

In [81]:
print("Classification Report of KNN after SMOTE :\n",classification_report(y_pred_knn_sm, y_test))

Classification Report of KNN after SMOTE :
               precision    recall  f1-score   support

           0       1.00      1.00      1.00     56784
           1       0.88      0.50      0.64       178

    accuracy                           1.00     56962
   macro avg       0.94      0.75      0.82     56962
weighted avg       1.00      1.00      1.00     56962

# Decision Tree

### Before SMOTE

### Creating Model

In [85]:
dt_classifier = DecisionTreeClassifier(random_state = 42)

### Training the Model

In [87]:
dt_classifier.fit(x_train, y_train)

DecisionTreeClassifier(random_state=42)

### y_pred_dt contains the values are obtained after traning the model and testing it with x_test features of the dataset

In [89]:
y_pred_dt = dt_classifier.predict(x_test)
y_pred_dt

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

### y_test contains the target values which were the part of dataset before splitting

In [91]:
y_test

183484    0
255448    0
244749    0
63919     0
11475     0
         ..
236778    0
127073    0
208502    0
263323    0
246221    0
Name: Class, Length: 56962, dtype: int64

### Accuracy of Decision Tree Before SMOTE

In [93]:
print("Accuracy of Decision Tree Before SMOTE : ",accuracy_score(y_pred_dt, y_test))

Accuracy of Decision Tree Before SMOTE :  0.9992451107756047

### Classification Report of Decision Tree Before SMOTE

In [95]:
print("Classification Report of Decsion Tree Before SMOTE : \n",classification_report(y_test, y_pred_dt))

Classification Report of Decsion Tree Before SMOTE :
               precision    recall  f1-score   support

           0       1.00      1.00      1.00     56861
           1       0.77      0.81      0.79       101

    accuracy                           1.00     56962
   macro avg       0.89      0.91      0.90     56962
weighted avg       1.00      1.00      1.00     56962

### After SMOTE

### Training the model

In [98]:
dt_classifier.fit(x_train_sm, y_train_sm)

DecisionTreeClassifier(random_state=42)

### y_pred_dt_sm contains the values which are predicated after the training the model and testing with x_test features of the dataset

In [100]:
y_pred_dt_sm = dt_classifier.predict(x_test)
y_pred_dt_sm

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

### y_test contains the target values which were the part of dataset before splitting

In [102]:
y_test

183484    0
255448    0
244749    0
63919     0
11475     0
         ..
236778    0
127073    0
208502    0
263323    0
246221    0
Name: Class, Length: 56962, dtype: int64

### Accuracy of Decision Tree After SMOTE

In [104]:
print("Accuracy of Decision Tree After SMOTE : ",accuracy_score(y_pred_dt_sm, y_test))

Accuracy of Decision Tree After SMOTE :  0.99750711000316

### Classification Report of Decision Tree After SMOTE

In [106]:
print("Classification_Report of Decision Tree After SMOTE :\n",classification_report(y_test, y_pred_dt_sm))

Classification_Report of Decision Tree After SMOTE :
               precision    recall  f1-score   support

           0       1.00      1.00      1.00     56861
           1       0.40      0.81      0.54       101

    accuracy                           1.00     56962
   macro avg       0.70      0.90      0.77     56962
weighted avg       1.00      1.00      1.00     56962

# Random Forest

### Before SMOTE

### Creating Model

In [110]:
rf_classifier = RandomForestClassifier(random_state = 42)

### Training the Model

In [112]:
rf_classifier.fit(x_train, y_train)

RandomForestClassifier(random_state=42)

### y_pred_rf contains the values which are predicated after the training the model and testing it with x_test features of the dataset

In [114]:
y_pred_rf = rf_classifier.predict(x_test)
y_pred_rf

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

### y_test contains the target values which were the part of dataset before splitting

In [116]:
y_test

183484    0
255448    0
244749    0
63919     0
11475     0
         ..
236778    0
127073    0
208502    0
263323    0
246221    0
Name: Class, Length: 56962, dtype: int64

### Accuracy of Random Forest Before SMOTE

In [118]:
print("Accuracy of Random Forest Before SMOTE :", accuracy_score(y_pred_rf, y_test))

Accuracy of Random Forest Before SMOTE : 0.9995084442259752

### Classification Report of Random Forest Before SMOTE

In [120]:
print("Classification Report of Random Forest Before SMOTE :\n",classification_report(y_test,y_pred_rf))

Classification Report of Random Forest Before SMOTE :
               precision    recall  f1-score   support

           0       1.00      1.00      1.00     56861
           1       0.93      0.78      0.85       101

    accuracy                           1.00     56962
   macro avg       0.96      0.89      0.92     56962
weighted avg       1.00      1.00      1.00     56962

### After SMOTE

### Traning the Model with SMOTE values of the Dataset

In [123]:
rf_classifier.fit(x_train_sm, y_train_sm)

RandomForestClassifier(random_state=42)

### y_pred_rf_sm contains the values which are predicted after traning the model and testing it with x_test features of the dataset

In [125]:
y_pred_rf_sm = rf_classifier.predict(x_test)
y_pred_rf_sm

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

### y_test contains the target values which were the part of dataset before splitting

In [127]:
y_test

183484    0
255448    0
244749    0
63919     0
11475     0
         ..
236778    0
127073    0
208502    0
263323    0
246221    0
Name: Class, Length: 56962, dtype: int64

### Accuracy of Random Forest after SMOTE

In [129]:
print("Accuracy of Random Forest after SMOTE : ",accuracy_score(y_pred_rf_sm, y_test))

Accuracy of Random Forest after SMOTE :  0.9994908886626171

### Classification Report of Random Forest after SMOTE

In [131]:
print("Classification Report of Random Forest after SMOTE :\n",classification_report(y_pred_rf_sm, y_test))

Classification Report of Random Forest after SMOTE :
               precision    recall  f1-score   support

           0       1.00      1.00      1.00     56864
           1       0.84      0.87      0.85        98

    accuracy                           1.00     56962
   macro avg       0.92      0.93      0.93     56962
weighted avg       1.00      1.00      1.00     56962

# SVC ( Support Vector Classifier )

### Before SMOTE

### Creating the Model and Training the model

In [135]:
modelv2 = SVC()
modelv2.fit(x_train, y_train)

SVC()

### y_pred_svc contains the values which are predicated after training the model and testing it with x_test features of the Dataset.

In [137]:
y_pred_svc = modelv2.predict(x_test)
y_pred_svc

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

### y_test contains the target values which were the part of dataset before splitting

In [139]:
y_test

183484    0
255448    0
244749    0
63919     0
11475     0
         ..
236778    0
127073    0
208502    0
263323    0
246221    0
Name: Class, Length: 56962, dtype: int64

### Accuracy of Support Vector Classifier Before SMOTE

In [141]:
print("Accuracy of Support Vector Classifier Before SMOTE :",accuracy_score(y_pred_svc, y_test))

Accuracy of Support Vector Classifier Before SMOTE : 0.9993153330290369

### Classification Report of Support Vector Classifier Before SMOTE

In [143]:
print("Classification Report of Support Vector Classifier Before SMOTE :\n",classification_report(y_test, y_pred_svc))

Classification Report of Support Vector Classifier Before SMOTE :
               precision    recall  f1-score   support

           0       1.00      1.00      1.00     56861
           1       0.93      0.66      0.77       101

    accuracy                           1.00     56962
   macro avg       0.96      0.83      0.89     56962
weighted avg       1.00      1.00      1.00     56962

### After SMOTE

### Creating the model and Traning the Model with SMOTE values of the dataset

In [ ]:
modelv2_svc = SVC()
modelv2.fit(x_train_sm, y_train_sm)

### y_pred_svc_sm contains the values which are predicted after traning the model and testing it with x_test features of the dataset

In [ ]:
y_pred_svc_sm = modelv2.predict(x_test)
y_pred_svc_sm

### y_test contains the target values which were the part of dataset before splitting

In [ ]:
y_test

### Accuracy of Support Vector Classifier after SMOTE

In [ ]:
print("Accuracy of Support Vector Classifier after SMOTE:", accuracy_score(y_pred_svc_sm , y_test))

### Classification Report of Support Vector Classifier after SMOTE

In [ ]:
print("Classification Report of Support Vector Classifier after SMOTE :\n",classification_report(y_test, y_pred_svc_sm))

# Conclusion

This project focused on detecting fraudulent credit card transactions using multiple machine learning models on a highly imbalanced dataset. Initial analysis showed that the dataset contained a very small number of fraudulent transactions compared to normal ones, which made the classification task challenging.

From the visualizations, it is clear that before applying SMOTE, the dataset was heavily imbalanced, causing models to achieve high accuracy while failing to detect many fraudulent cases. This was reflected in lower recall values for the fraud class.

After applying SMOTE, the class distribution became balanced, which significantly improved the recall of most models. The recall comparison graph clearly shows that models became much better at identifying fraudulent transactions after balancing the dataset. However, this improvement came with a trade-off in precision, as the number of false positives increased.

Among all the models, Random Forest performed the best after applying SMOTE, achieving a strong balance between precision and recall. The confusion matrix of the Random Forest model further confirms its effectiveness in correctly identifying both normal and fraudulent transactions.

Overall, this project demonstrates that:

* Class imbalance significantly affects model performance
* Accuracy alone is not a reliable metric in such cases
* SMOTE is an effective technique for improving fraud detection
* There is a trade-off between precision and recall
* Ensemble models like Random Forest are more robust for real-world problems

In real-world fraud detection systems, recall is more important than precision, as missing fraudulent transactions can lead to serious financial losses. This project successfully highlights the importance of proper data handling, model evaluation, and visualization in solving real-world machine learning problems.

In [ ]:
models = ["Logistic", "KNN", "Decision Tree", "Random Forest", "SVM"]

recall_before = [0.62, 0.79, 0.81, 0.78, 0.66]
recall_after = [0.94, 0.50, 0.81, 0.87, 0.91]

x = np.arange(len(models))

plt.figure()
plt.bar(x - 0.2, recall_before, 0.4, label='Before SMOTE')
plt.bar(x + 0.2, recall_after, 0.4, label='After SMOTE')

plt.xticks(x, models)
plt.ylabel("Recall")
plt.title("Recall Comparison Before vs After SMOTE")
plt.legend()
plt.show()